### ISSUE TITLE
No money

### ISSUE THREAD

**Issue by gergewgr** [TtvNekix/nek_deliveryjob#1]
You don’t give away the money after you get the job done.

**Comment by TtvNekix** [comment]
ESX versión or QBCore versión?

**Comment by gergewgr** [comment]
esx legacy

**Comment by TtvNekix** [comment]
The script was developed for 1.2 version but i'm going to do a legacy versión, sorry for the inconvenience

**Comment by gergewgr** [comment]
no problem only i am developing only in the meantime i try a lot of novelties otherwise beautiful design congratulations
