### ISSUE TITLE
no marker

### ISSUE THREAD

**Issue by mikel13200** [TtvNekix/nek_deliveryjob#2]
why i need to restart the script so that the marker will top up?

**Comment by TtvNekix** [comment]
i fix that, wait a minute and i upload the fix

**Comment by TtvNekix** [comment]
I have the fix for esx, if you use qbcore you need to wait a little bit more

**Comment by TtvNekix** [comment]
repaired

**Comment by mikel13200** [comment]
![image](https://user-images.githubusercontent.com/78634549/177321654-172851a3-77f7-4bff-98f9-d50d7cfeca02.png) this is the error

**Comment by mikel13200** [comment]
im using esx legacy

**Comment by TtvNekix** [comment]
i program this script in 1.2, try now, i change the line

**Comment by mikel13200** [comment]
still the same error sir.

**Comment by TtvNekix** [comment]
send me PlayerData printed please

print(json.encode(PlayerData))

**Comment by mikel13200** [comment]
where should i put that one sir?

**Comment by TtvNekix** [comment]
after line 22

**Comment by mikel13200** [comment]
![image](https://user-images.githubusercontent.com/78634549/177324779-b6795d58-192a-454d-8f5f-d8b6eabef401.png)

**Comment by TtvNekix** [comment]
mmmm change PlayerData with PlayerData.job.name

**Comment by mikel13200** [comment]
![image](https://user-images.githubusercontent.com/78634549/177325195-9b5c901c-70b7-42d2-bc33-d273d1f126a8.png)

**Comment by mikel13200** [comment]
i change the config deliverjob name to burgershot instead of delivery

**Comment by TtvNekix** [comment]
ok, can you try if you get some error again?

**Comment by mikel13200** [comment]
yeah, still the same, need to restart the script so that the market will be pop up

**Comment by TtvNekix** [comment]
change your job with the script started and wait a seconds. If it doesn't work, we need to try a slowest form, wait a second.

**Comment by TtvNekix** [comment]
Add this to your script 

CreateThread(function()
while true do
PlayerData = ESX.GetPlayerData()
Wait(2000)
end)

**Comment by mikel13200** [comment]
i add end cuz u lack of it then this one works
CreateThread(function()
    while true do
    PlayerData = ESX.GetPlayerData()
    Wait(2000)
    end
end)

**Comment by mikel13200** [comment]
thank you for the effort sir for the response

**Comment by mikel13200** [comment]
btw sir last question? can i make it two job on it? like other marker for the taco and only taco can access it? and burgershot only burgershot can access the marker?

**Comment by TtvNekix** [comment]
yes, duplicate the script and change the job in config <3

**Comment by mikel13200** [comment]
['JobName'] = 'burgershot',
    ['ActionKey'] = 38, -- E
    ['FinalPayout'] = {
        ['Min'] = 500,
        ['Max'] = 1000
    },
    ['Blips'] = {
        {
            ['x'] = -1177.998,
            ['y'] = -892.051,
            ['z'] = 13.757,
            ['sprite'] = 616,
            ['color'] = 47,
            ['scale'] = 0.75,
            ['label'] = "Delivery Center",
        }
    },
    ['Uniforms'] = { 
        ['Male'] = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 13,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 11,
            ['pants_1'] = 96,   ['pants_2'] = 0,
            ['shoes_1'] = 10,    ['shoes_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['helmet_1'] = -1,    ['helmet_2'] = 0
        },
        ['Female'] = { -- Edit female clothes, i can't find good clothes for females peds
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 13,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 11,
            ['pants_1'] = 96,   ['pants_2'] = 0,
            ['shoes_1'] = 10,    ['shoes_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['helmet_1'] = -1,    ['helmet_2'] = 0
        } 
    },
    ['Base'] = {
        {
            ['coords'] = vec3(-1177.998, -892.051, 13.757),
        }
    },
    ['Prop'] = {
        ['Model'] = 'prop_cs_cardbox_01',
        ['x'] = -1178.628,
        ['y'] = -887.744,
        ['z'] = 12.807, 
    },
    ['Vehicles'] = {
        ['Spawner'] = {
            ['coords'] = {
                vec3(-1168.39, -882.855, 14.137),
            },
            ['rotation'] = 302.2133,
        },
        ['Deleter'] = vec3(-1173.832, -900.722, 15.0),
        ['Plate'] = "DELIVERY",
        ['Cars'] = {
            'rumpo',
        },
    },
    ['Destinations'] = { -- Add more Destinations writing more vec3(x, y, z)
        vec3(-284.3353, -601.2335, 33.5532),
        vec3(-292.3353, -601.2335, 33.5532),
    },



    --[[ TACO ]]
    ['JobName'] = 'taco',
    ['ActionKey'] = 38, -- E
    ['FinalPayout'] = {
        ['Min'] = 500,
        ['Max'] = 1000
    },
    ['Blips'] = {
        {
            ['x'] = -1177.998,
            ['y'] = -892.051,
            ['z'] = 13.757,
            ['sprite'] = 616,
            ['color'] = 47,
            ['scale'] = 0.75,
            ['label'] = "Delivery Center",
        }
    },
    ['Uniforms'] = { 
        ['Male'] = {
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 13,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 11,
            ['pants_1'] = 96,   ['pants_2'] = 0,
            ['shoes_1'] = 10,    ['shoes_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['helmet_1'] = -1,    ['helmet_2'] = 0
        },
        ['Female'] = { -- Edit female clothes, i can't find good clothes for females peds
            ['tshirt_1'] = 15,  ['tshirt_2'] = 0,
            ['torso_1'] = 13,   ['torso_2'] = 3,
            ['decals_1'] = 0,   ['decals_2'] = 0,
            ['arms'] = 11,
            ['pants_1'] = 96,   ['pants_2'] = 0,
            ['shoes_1'] = 10,    ['shoes_2'] = 0,
            ['chain_1'] = 0,    ['chain_2'] = 0,
            ['helmet_1'] = -1,    ['helmet_2'] = 0
        } 
    },
    ['Base'] = {
        {
            ['coords'] = vec3(-1177.998, -892.051, 13.757),
        }
    },
    ['Prop'] = {
        ['Model'] = 'prop_cs_cardbox_01',
        ['x'] = -1178.628,
        ['y'] = -887.744,
        ['z'] = 12.807, 
    },
    ['Vehicles'] = {
        ['Spawner'] = {
            ['coords'] = {
                vec3(-1168.39, -882.855, 14.137),
            },
            ['rotation'] = 302.2133,
        },
        ['Deleter'] = vec3(-1173.832, -900.722, 15.0),
        ['Plate'] = "DELIVERY",
        ['Cars'] = {
            'rumpo',
        },
    },
    ['Destinations'] = { -- Add more Destinations writing more vec3(x, y, z)
        vec3(-284.3353, -601.2335, 33.5532),
        vec3(-292.3353, -601.2335, 33.5532),
    },

**Comment by mikel13200** [comment]
like this?

**Comment by TtvNekix** [comment]
copy and paste all the script
